cfg: !!python/object/apply:types.SimpleNamespace
  state:
    general: !!python/object/apply:types.SimpleNamespace
      state:
        dataset: uci
        device: cpu
        name: digress
        seed: 42
    model: !!python/object/apply:types.SimpleNamespace
      state:
        categorization_method: statistical
        dropout: 0.1
        hidden_dims: !!python/tuple
        - 128
        - 64
        - 32
        input_dims: &id001 !!python/tuple
        - 100
        - 100
        - 1
        marginal_dist: !!python/object/apply:torch._utils._rebuild_tensor_v2
        - !!python/object/apply:torch.storage._load_from_bytes
          - !!binary |
            gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
            AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
            aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
            Z2UKcQFYCgAAADExMzYyNDcxMzZxAlgDAAAAY3B1cQNLCk50cQRRLoACXXEAWAoAAAAxMTM2MjQ3
            MTM2cQFhLgoAAAAAAAAAfY9wPwAAAAAAAAAAAAAAAAAAAAAAAAAAmN0MPQAAAAAAAAAAOFXUPA==
        - 0
        - !!python/tuple
          - 10
        - !!python/tuple
          - 1
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
        n_heads: 4
        n_layers: 3
        num_diffusion_steps: 500
        num_node_categories: 10
        output_dims: *id001
        time_embedding_dim: 32
    train: !!python/object/apply:types.SimpleNamespace
      state:
        batch_size: 8
        edge_weight: 1.0
        epochs: 2
        global_weight: 0.5
        log_steps: 1
        lr: 0.0001
        min_lr: 1.0e-06
        node_weight: 1.0
        weight_decay: 1.0e-05
