cfg: !!python/object/apply:types.SimpleNamespace
  state:
    general: !!python/object/apply:types.SimpleNamespace
      state:
        dataset: btc_alpha
        device: cpu
        name: digress
        seed: 42
    model: !!python/object/apply:types.SimpleNamespace
      state:
        categorization_method: statistical
        dropout: 0.1
        hidden_dims: &id001 !!python/tuple
        - 32
        - 16
        - 8
        input_dims: *id001
        n_heads: 4
        n_layers: 3
        num_diffusion_steps: 500
        num_node_categories: 10
        output_dims: *id001
        time_embedding_dim: 32
    train: !!python/object/apply:types.SimpleNamespace
      state:
        batch_size: 4
        edge_weight: 1.0
        epochs: 100
        global_weight: 0.5
        log_steps: 1
        lr: 0.0001
        min_lr: 1.0e-06
        node_weight: 1.0
        weight_decay: 1.0e-05
